local Vesper = {}

Vesper.config = {
	terminal_colors = true,
	undercurl = true,
	underline = true,
	bold = true,
	italic = {
		strings = true,
		emphasis = true,
		comments = true,
		operators = false,
		folds = true,
	},
	strikethrough = true,
	invert_selection = false,
	invert_signs = false,
	invert_tabline = false,
	invert_intend_guides = false,
	inverse = true,
	contrast = "",
	palette_overrides = {},
	overrides = {},
	dim_inactive = false,
	transparent_mode = false,
}

Vesper.palette = {
	dark0_hard = "#1d2021",
	dark0 = "#282828",
	dark0_soft = "#32302f",
	dark1 = "#3c3836",
	dark2 = "#504945",
	dark3 = "#665c54",
	dark4 = "#7c6f64",
	light0_hard = "#f9f5d7",
	light0 = "#fbf1c7",
	light0_soft = "#f2e5bc",
	light1 = "#ebdbb2",
	light2 = "#d5c4a1",
	light3 = "#bdae93",
	light4 = "#a89984",
	bright_red = "#fb4934",
	bright_green = "#b8bb26",
	bright_yellow = "#fabd2f",
	bright_blue = "#83a598",
	bright_purple = "#d3869b",
	bright_aqua = "#8ec07c",
	bright_orange = "#fe8019",
	neutral_red = "#cc241d",
	neutral_green = "#98971a",
	neutral_yellow = "#d79921",
	neutral_blue = "#458588",
	neutral_purple = "#b16286",
	neutral_aqua = "#689d6a",
	neutral_orange = "#d65d0e",
	faded_red = "#9d0006",
	faded_green = "#79740e",
	faded_yellow = "#b57614",
	faded_blue = "#076678",
	faded_purple = "#8f3f71",
	faded_aqua = "#427b58",
	faded_orange = "#af3a03",
	dark_red_hard = "#792329",
	dark_red = "#722529",
	dark_red_soft = "#7b2c2f",
	light_red_hard = "#fc9690",
	light_red = "#fc9487",
	light_red_soft = "#f78b7f",
	dark_green_hard = "#5a633a",
	dark_green = "#62693e",
	dark_green_soft = "#686d43",
	light_green_hard = "#d3d6a5",
	light_green = "#d5d39b",
	light_green_soft = "#cecb94",
	dark_aqua_hard = "#3e4934",
	dark_aqua = "#49503b",
	dark_aqua_soft = "#525742",
	light_aqua_hard = "#e6e9c1",
	light_aqua = "#e8e5b5",
	light_aqua_soft = "#e1dbac",
	gray = "#928374",
}

local function get_colors()
  local p = Vesper.palette
  local config = Vesper.config

  for color, hex in pairs(config.palette_overrides) do
    p[color] = hex
  end

  local bg = vim.o.background
  local contrast = config.contrast
  local color_groups = {
    dark = {
      bg0 = p.dark0,
      bg1 = p.dark1,
      bg2 = p.dark2,
      bg3 = p.dark3,
      bg4 = p.dark4,
      fg0 = p.light0,
      fg1 = p.light1,
      fg2 = p.light2,
      fg3 = p.light3,
      fg4 = p.light4,
      red = p.bright_red,
      green = p.bright_green,
      yellow = p.bright_yellow,
      blue = p.bright_blue,
      purple = p.bright_purple,
      aqua = p.bright_aqua,
      orange = p.bright_orange,
      neutral_red = p.neutral_red,
      neutral_green = p.neutral_green,
      neutral_yellow = p.neutral_yellow,
      neutral_blue = p.neutral_blue,
      neutral_purple = p.neutral_purple,
      neutral_aqua = p.neutral_aqua,
      dark_red = p.dark_red,
      dark_green = p.dark_green,
      dark_aqua = p.dark_aqua,
      gray = p.gray,
    },
    light = {
      bg0 = p.light0,
      bg1 = p.light1,
      bg2 = p.light2,
      bg3 = p.light3,
      bg4 = p.light4,
      fg0 = p.dark0,
      fg1 = p.dark1,
      fg2 = p.dark2,
      fg3 = p.dark3,
      fg4 = p.dark4,
      red = p.faded_red,
      green = p.faded_green,
      yellow = p.faded_yellow,
      blue = p.faded_blue,
      purple = p.faded_purple,
      aqua = p.faded_aqua,
      orange = p.faded_orange,
      neutral_red = p.neutral_red,
      neutral_green = p.neutral_green,
      neutral_yellow = p.neutral_yellow,
      neutral_blue = p.neutral_blue,
      neutral_purple = p.neutral_purple,
      neutral_aqua = p.neutral_aqua,
      dark_red = p.light_red,
      dark_green = p.light_green,
      dark_aqua = p.light_aqua,
      gray = p.gray,
    },
  }
  if contrast ~= nil and contrast ~= "" then
    color_groups[bg].bg0 = p[bg .. "0_" .. contrast]
    color_groups[bg].dark_red = p[bg .. "_red_" .. contrast]
    color_groups[bg].dark_green = p[bg .. "_green_" .. contrast]
    color_groups[bg].dark_aqua = p[bg .. "_aqua_" .. contrast]
  end

  return color_groups[bg]
end

local function get_groups()
  local colors = get_colors()
  local config = Vesper.config

  if config.terminal_colors then
    local term_colors = {
      colors.bg0,
      colors.neutral_red,
      colors.neutral_green,
      colors.neutral_yellow,
      colors.neutral_blue,
      colors.neutral_purple,
      colors.neutral_aqua,
      colors.fg4,
      colors.gray,
      colors.red,
      colors.green,
      colors.yellow,
      colors.blue,
      colors.purple,
      colors.aqua,
      colors.fg1,
    }
    for index, value in ipairs(term_colors) do
      vim.g["terminal_color_" .. index - 1] = value
    end
  end

local groups = {
    vesperfg0 = { fg = colors.fg0 },
    vesperfg1 = { fg = colors.fg1 },
    vesperfg2 = { fg = colors.fg2 },
    vesperfg3 = { fg = colors.fg3 },
    vesperfg4 = { fg = colors.fg4 },
    vespergray = { fg = colors.gray },
    vesperbg0 = { fg = colors.bg0 },
    vesperbg1 = { fg = colors.bg1 },
    vesperbg2 = { fg = colors.bg2 },
    vesperbg3 = { fg = colors.bg3 },
    vesperbg4 = { fg = colors.bg4 },
    vesperred = { fg = colors.red },
    vesperredbold = { fg = colors.red, bold = config.bold },
    vespergreen = { fg = colors.green },
    vespergreenbold = { fg = colors.green, bold = config.bold },
    vesperyellow = { fg = colors.yellow },
    vesperyellowbold = { fg = colors.yellow, bold = config.bold },
    vesperblue = { fg = colors.blue },
    vesperbluebold = { fg = colors.blue, bold = config.bold },
    vesperpurple = { fg = colors.purple },
    vesperpurplebold = { fg = colors.purple, bold = config.bold },
    vesperaqua = { fg = colors.aqua },
    vesperaquabold = { fg = colors.aqua, bold = config.bold },
    vesperorange = { fg = colors.orange },
    vesperorangebold = { fg = colors.orange, bold = config.bold },
    vesperredsign = config.transparent_mode and { fg = colors.red, reverse = config.invert_signs }
      or { fg = colors.red, bg = colors.bg1, reverse = config.invert_signs },
    VesperGreenSign = config.transparent_mode and { fg = colors.green, reverse = config.invert_signs }
      or { fg = colors.green, bg = colors.bg1, reverse = config.invert_signs },
    VesperYellowSign = config.transparent_mode and { fg = colors.yellow, reverse = config.invert_signs }
      or { fg = colors.yellow, bg = colors.bg1, reverse = config.invert_signs },
    VesperBlueSign = config.transparent_mode and { fg = colors.blue, reverse = config.invert_signs }
      or { fg = colors.blue, bg = colors.bg1, reverse = config.invert_signs },
    VesperPurpleSign = config.transparent_mode and { fg = colors.purple, reverse = config.invert_signs }
      or { fg = colors.purple, bg = colors.bg1, reverse = config.invert_signs },
    VesperAquaSign = config.transparent_mode and { fg = colors.aqua, reverse = config.invert_signs }
      or { fg = colors.aqua, bg = colors.bg1, reverse = config.invert_signs },
    VesperOrangeSign = config.transparent_mode and { fg = colors.orange, reverse = config.invert_signs }
      or { fg = colors.orange, bg = colors.bg1, reverse = config.invert_signs },
    VesperRedUnderline = { undercurl = config.undercurl, sp = colors.red },
    VesperGreenUnderline = { undercurl = config.undercurl, sp = colors.green },
    VesperYellowUnderline = { undercurl = config.undercurl, sp = colors.yellow },
    VesperBlueUnderline = { undercurl = config.undercurl, sp = colors.blue },
    VesperPurpleUnderline = { undercurl = config.undercurl, sp = colors.purple },
    VesperAquaUnderline = { undercurl = config.undercurl, sp = colors.aqua },
    VesperOrangeUnderline = { undercurl = config.undercurl, sp = colors.orange },
    Normal = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg0 },
    NormalFloat = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg1 },
    NormalNC = config.dim_inactive and { fg = colors.fg0, bg = colors.bg1 } or { link = "Normal" },
    CursorLine = { bg = colors.bg1 },
    CursorColumn = { link = "CursorLine" },
    TabLineFill = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
    TabLineSel = { fg = colors.green, bg = colors.bg1, reverse = config.invert_tabline },
    TabLine = { link = "TabLineFill" },
    MatchParen = { bg = colors.bg3, bold = config.bold },
    ColorColumn = { bg = colors.bg1 },
    Conceal = { fg = colors.blue },
    CursorLineNr = { fg = colors.yellow, bg = colors.bg1 },
    NonText = { link = "VesperBg2" },
    SpecialKey = { link = "VesperFg4" },
    Visual = { bg = colors.bg3, reverse = config.invert_selection },
    VisualNOS = { link = "Visual" },
    Search = { fg = colors.yellow, bg = colors.bg0, reverse = config.inverse },
    IncSearch = { fg = colors.orange, bg = colors.bg0, reverse = config.inverse },
    CurSearch = { link = "IncSearch" },
    QuickFixLine = { link = "VesperPurple" },
    Underlined = { fg = colors.blue, underline = config.underline },
    StatusLine = { fg = colors.bg2, bg = colors.fg1, reverse = config.inverse },
    StatusLineNC = { fg = colors.bg1, bg = colors.fg4, reverse = config.inverse },
    WinBar = { fg = colors.fg4, bg = colors.bg0 },
    WinBarNC = { fg = colors.fg3, bg = colors.bg1 },
    WinSeparator = config.transparent_mode and { fg = colors.bg3, bg = nil } or { fg = colors.bg3, bg = colors.bg0 },
    WildMenu = { fg = colors.blue, bg = colors.bg2, bold = config.bold },
    Directory = { link = "VesperBlueBold" },
    Title = { link = "VesperGreenBold" },
    ErrorMsg = { fg = colors.bg0, bg = colors.red, bold = config.bold },
    MoreMsg = { link = "VesperYellowBold" },
    ModeMsg = { link = "VesperYellowBold" },
    Question = { link = "VesperOrangeBold" },
    WarningMsg = { link = "VesperRedBold" },
    LineNr = { fg = colors.bg4 },
    SignColumn = config.transparent_mode and { bg = nil } or { bg = colors.bg1 },
    Folded = { fg = colors.gray, bg = colors.bg1, italic = config.italic.folds },
    FoldColumn = config.transparent_mode and { fg = colors.gray, bg = nil } or { fg = colors.gray, bg = colors.bg1 },
    Cursor = { reverse = config.inverse },
    vCursor = { link = "Cursor" },
    iCursor = { link = "Cursor" },
    lCursor = { link = "Cursor" },
    Special = { link = "VesperOrange" },
    Comment = { fg = colors.gray, italic = config.italic.comments },
    Todo = { fg = colors.bg0, bg = colors.yellow, bold = config.bold, italic = config.italic.comments },
    Done = { fg = colors.orange, bold = config.bold, italic = config.italic.comments },
    Error = { fg = colors.red, bold = config.bold, reverse = config.inverse },
    Statement = { link = "VesperRed" },
    Conditional = { link = "VesperRed" },
    Repeat = { link = "VesperRed" },
    Label = { link = "VesperRed" },
    Exception = { link = "VesperRed" },
    Operator = { fg = colors.orange, italic = config.italic.operators },
    Keyword = { link = "VesperRed" },
    Identifier = { link = "VesperBlue" },
    Function = { link = "VesperGreenBold" },
    PreProc = { link = "VesperAqua" },
    Include = { link = "VesperAqua" },
    Define = { link = "VesperAqua" },
    Macro = { link = "VesperAqua" },
    PreCondit = { link = "VesperAqua" },
    Constant = { link = "VesperPurple" },
    Character = { link = "VesperPurple" },
    String = { fg = colors.green, italic = config.italic.strings },
    Boolean = { link = "VesperPurple" },
    Number = { link = "VesperPurple" },
    Float = { link = "VesperPurple" },
    Type = { link = "VesperYellow" },
    StorageClass = { link = "VesperOrange" },
    Structure = { link = "VesperAqua" },
    Typedef = { link = "VesperYellow" },
    Pmenu = { fg = colors.fg1, bg = colors.bg2 },
    PmenuSel = { fg = colors.bg2, bg = colors.blue, bold = config.bold },
    PmenuSbar = { bg = colors.bg2 },
    PmenuThumb = { bg = colors.bg4 },
    DiffDelete = { bg = colors.dark_red },
    DiffAdd = { bg = colors.dark_green },
    DiffChange = { bg = colors.dark_aqua },
    DiffText = { bg = colors.yellow, fg = colors.bg0 },
    SpellCap = { link = "VesperBlueUnderline" },
    SpellBad = { link = "VesperRedUnderline" },
    SpellLocal = { link = "VesperAquaUnderline" },
    SpellRare = { link = "VesperPurpleUnderline" },
    Whitespace = { fg = colors.bg2 },
    DiagnosticError = { link = "VesperRed" },
    DiagnosticSignError = { link = "VesperRedSign" },
    DiagnosticUnderlineError = { link = "VesperRedUnderline" },
    DiagnosticWarn = { link = "VesperYellow" },
    DiagnosticSignWarn = { link = "VesperYellowSign" },
    DiagnosticUnderlineWarn = { link = "VesperYellowUnderline" },
    DiagnosticInfo = { link = "VesperBlue" },
    DiagnosticSignInfo = { link = "VesperBlueSign" },
    DiagnosticUnderlineInfo = { link = "VesperBlueUnderline" },
    DiagnosticHint = { link = "VesperAqua" },
    DiagnosticSignHint = { link = "VesperAquaSign" },
    DiagnosticUnderlineHint = { link = "VesperAquaUnderline" },
    DiagnosticFloatingError = { link = "VesperRed" },
    DiagnosticFloatingWarn = { link = "VesperOrange" },
    DiagnosticFloatingInfo = { link = "VesperBlue" },
    DiagnosticFloatingHint = { link = "VesperAqua" },
    DiagnosticVirtualTextError = { link = "VesperRed" },
    DiagnosticVirtualTextWarn = { link = "VesperYellow" },
    DiagnosticVirtualTextInfo = { link = "VesperBlue" },
    DiagnosticVirtualTextHint = { link = "VesperAqua" },
    DiagnosticOk = { link = "VesperGreenSign" },
    LspReferenceRead = { link = "VesperYellowBold" },
    LspReferenceText = { link = "VesperYellowBold" },
    LspReferenceWrite = { link = "VesperOrangeBold" },
    LspCodeLens = { link = "VesperGray" },
    LspSignatureActiveParameter = { link = "Search" },
    gitcommitSelectedFile = { link = "VesperGreen" },
    gitcommitDiscardedFile = { link = "VesperRed" },
    GitSignsAdd = { link = "VesperGreen" },
    GitSignsChange = { link = "VesperAqua" },
    GitSignsDelete = { link = "VesperRed" },
    NvimTreeSymlink = { fg = colors.neutral_aqua },
    NvimTreeRootFolder = { fg = colors.neutral_purple, bold = true },
    NvimTreeFolderIcon = { fg = colors.neutral_blue, bold = true },
    NvimTreeFileIcon = { fg = colors.light2 },
    NvimTreeExecFile = { fg = colors.neutral_green, bold = true },
    NvimTreeOpenedFile = { fg = colors.bright_red, bold = true },
    NvimTreeSpecialFile = { fg = colors.neutral_yellow, bold = true, underline = true },
    NvimTreeImageFile = { fg = colors.neutral_purple },
    NvimTreeIndentMarker = { fg = colors.dark3 },
    NvimTreeGitDirty = { fg = colors.neutral_yellow },
    NvimTreeGitStaged = { fg = colors.neutral_yellow },
    NvimTreeGitMerge = { fg = colors.neutral_purple },
    NvimTreeGitRenamed = { fg = colors.neutral_purple },
    NvimTreeGitNew = { fg = colors.neutral_yellow },
    NvimTreeGitDeleted = { fg = colors.neutral_red },
    NvimTreeWindowPicker = { bg = colors.aqua },
    debugPC = { link = "DiffAdd" },
    debugBreakpoint = { link = "VesperRedSign" },
    StartifyBracket = { link = "VesperFg3" },
    StartifyFile = { link = "VesperFg1" },
    StartifyNumber = { link = "VesperBlue" },
    StartifyPath = { link = "VesperGray" },
    StartifySlash = { link = "VesperGray" },
    StartifySection = { link = "VesperYellow" },
    StartifySpecial = { link = "VesperBg2" },
    StartifyHeader = { link = "VesperOrange" },
    StartifyFooter = { link = "VesperBg2" },
    StartifyVar = { link = "StartifyPath" },
    StartifySelect = { link = "Title" },
    DirvishPathTail = { link = "VesperAqua" },
    DirvishArg = { link = "VesperYellow" },
    netrwDir = { link = "VesperAqua" },
    netrwClassify = { link = "VesperAqua" },
    netrwLink = { link = "VesperGray" },
    netrwSymLink = { link = "VesperFg1" },
    netrwExe = { link = "VesperYellow" },
    netrwComment = { link = "VesperGray" },
    netrwList = { link = "VesperBlue" },
    netrwHelpCmd = { link = "VesperAqua" },
    netrwCmdSep = { link = "VesperFg3" },
    netrwVersion = { link = "VesperGreen" },
    NERDTreeDir = { link = "VesperAqua" },
    NERDTreeDirSlash = { link = "VesperAqua" },
    NERDTreeOpenable = { link = "VesperOrange" },
    NERDTreeClosable = { link = "VesperOrange" },
    NERDTreeFile = { link = "VesperFg1" },
    NERDTreeExecFile = { link = "VesperYellow" },
    NERDTreeUp = { link = "VesperGray" },
    NERDTreeCWD = { link = "VesperGreen" },
    NERDTreeHelp = { link = "VesperFg1" },
    NERDTreeToggleOn = { link = "VesperGreen" },
    NERDTreeToggleOff = { link = "VesperRed" },
    CocErrorSign = { link = "VesperRedSign" },
    CocWarningSign = { link = "VesperOrangeSign" },
    CocInfoSign = { link = "VesperBlueSign" },
    CocHintSign = { link = "VesperAquaSign" },
    CocErrorFloat = { link = "VesperRed" },
    CocWarningFloat = { link = "VesperOrange" },
    CocInfoFloat = { link = "VesperBlue" },
    CocHintFloat = { link = "VesperAqua" },
    CocDiagnosticsError = { link = "VesperRed" },
    CocDiagnosticsWarning = { link = "VesperOrange" },
    CocDiagnosticsInfo = { link = "VesperBlue" },
    CocDiagnosticsHint = { link = "VesperAqua" },
    CocSelectedText = { link = "VesperRed" },
    CocMenuSel = { link = "PmenuSel" },
    CocCodeLens = { link = "VesperGray" },
    CocErrorHighlight = { link = "VesperRedUnderline" },
    CocWarningHighlight = { link = "VesperOrangeUnderline" },
    CocInfoHighlight = { link = "VesperBlueUnderline" },
    CocHintHighlight = { link = "VesperAquaUnderline" },
    TelescopeNormal = { link = "VesperFg1" },
    TelescopeSelection = { link = "VesperOrangeBold" },
    TelescopeSelectionCaret = { link = "VesperRed" },
    TelescopeMultiSelection = { link = "VesperGray" },
    TelescopeBorder = { link = "TelescopeNormal" },
    TelescopePromptBorder = { link = "TelescopeNormal" },
    TelescopeResultsBorder = { link = "TelescopeNormal" },
    TelescopePreviewBorder = { link = "TelescopeNormal" },
    TelescopeMatching = { link = "VesperBlue" },
    TelescopePromptPrefix = { link = "VesperRed" },
    TelescopePrompt = { link = "TelescopeNormal" },
    CmpItemAbbr = { link = "VesperFg0" },
    CmpItemAbbrDeprecated = { link = "VesperFg1" },
    CmpItemAbbrMatch = { link = "VesperBlueBold" },
    CmpItemAbbrMatchFuzzy = { link = "VesperBlueUnderline" },
    CmpItemMenu = { link = "VesperGray" },
    CmpItemKindText = { link = "VesperOrange" },
    CmpItemKindVariable = { link = "VesperOrange" },
    CmpItemKindMethod = { link = "VesperBlue" },
    CmpItemKindFunction = { link = "VesperBlue" },
    CmpItemKindConstructor = { link = "VesperYellow" },
    CmpItemKindUnit = { link = "VesperBlue" },
    CmpItemKindField = { link = "VesperBlue" },
    CmpItemKindClass = { link = "VesperYellow" },
    CmpItemKindInterface = { link = "VesperYellow" },
    CmpItemKindModule = { link = "VesperBlue" },
    CmpItemKindProperty = { link = "VesperBlue" },
    CmpItemKindValue = { link = "VesperOrange" },
    CmpItemKindEnum = { link = "VesperYellow" },
    CmpItemKindOperator = { link = "VesperYellow" },
    CmpItemKindKeyword = { link = "VesperPurple" },
    CmpItemKindEvent = { link = "VesperPurple" },
    CmpItemKindReference = { link = "VesperPurple" },
    CmpItemKindColor = { link = "VesperPurple" },
    CmpItemKindSnippet = { link = "VesperGreen" },
    CmpItemKindFile = { link = "VesperBlue" },
    CmpItemKindFolder = { link = "VesperBlue" },
    CmpItemKindEnumMember = { link = "VesperAqua" },
    CmpItemKindConstant = { link = "VesperOrange" },
    CmpItemKindStruct = { link = "VesperYellow" },
    CmpItemKindTypeParameter = { link = "VesperYellow" },
    diffAdded = { link = "DiffAdd" },
    diffRemoved = { link = "DiffDelete" },
    diffChanged = { link = "DiffChange" },
    diffFile = { link = "VesperOrange" },
    diffNewFile = { link = "VesperYellow" },
    diffOldFile = { link = "VesperOrange" },
    diffLine = { link = "VesperBlue" },
    diffIndexLine = { link = "diffChanged" },
    NavicIconsFile = { link = "VesperBlue" },
    NavicIconsModule = { link = "VesperOrange" },
    NavicIconsNamespace = { link = "VesperBlue" },
    NavicIconsPackage = { link = "VesperAqua" },
    NavicIconsClass = { link = "VesperYellow" },
    NavicIconsMethod = { link = "VesperBlue" },
    NavicIconsProperty = { link = "VesperAqua" },
    NavicIconsField = { link = "VesperPurple" },
    NavicIconsConstructor = { link = "VesperBlue" },
    NavicIconsEnum = { link = "VesperPurple" },
    NavicIconsInterface = { link = "VesperGreen" },
    NavicIconsFunction = { link = "VesperBlue" },
    NavicIconsVariable = { link = "VesperPurple" },
    NavicIconsConstant = { link = "VesperOrange" },
    NavicIconsString = { link = "VesperGreen" },
    NavicIconsNumber = { link = "VesperOrange" },
    NavicIconsBoolean = { link = "VesperOrange" },
    NavicIconsArray = { link = "VesperOrange" },
    NavicIconsObject = { link = "VesperOrange" },
    NavicIconsKey = { link = "VesperAqua" },
    NavicIconsNull = { link = "VesperOrange" },
    NavicIconsEnumMember = { link = "VesperYellow" },
    NavicIconsStruct = { link = "VesperPurple" },
    NavicIconsEvent = { link = "VesperYellow" },
    NavicIconsOperator = { link = "VesperRed" },
    NavicIconsTypeParameter = { link = "VesperRed" },
    NavicText = { link = "VesperWhite" },
    NavicSeparator = { link = "VesperWhite" },
    htmlTag = { link = "VesperAquaBold" },
    htmlEndTag = { link = "VesperAquaBold" },
    htmlTagName = { link = "VesperBlue" },
    htmlArg = { link = "VesperOrange" },
    htmlTagN = { link = "VesperFg1" },
    htmlSpecialTagName = { link = "VesperBlue" },
    htmlLink = { fg = colors.fg4, underline = config.underline },
    htmlSpecialChar = { link = "VesperRed" },
    htmlBold = { fg = colors.fg0, bg = colors.bg0, bold = config.bold },
    htmlBoldUnderline = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, underline = config.underline },
    htmlBoldItalic = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, italic = true },
    htmlBoldUnderlineItalic = {
      fg = colors.fg0,
      bg = colors.bg0,
      bold = config.bold,
      italic = true,
      underline = config.underline,
    },
    htmlUnderline = { fg = colors.fg0, bg = colors.bg0, underline = config.underline },
    htmlUnderlineItalic = {
      fg = colors.fg0,
      bg = colors.bg0,
      italic = true,
      underline = config.underline,
    },
    htmlItalic = { fg = colors.fg0, bg = colors.bg0, italic = true },
    xmlTag = { link = "VesperAquaBold" },
    xmlEndTag = { link = "VesperAquaBold" },
    xmlTagName = { link = "VesperBlue" },
    xmlEqual = { link = "VesperBlue" },
    docbkKeyword = { link = "VesperAquaBold" },
    xmlDocTypeDecl = { link = "VesperGray" },
    xmlDocTypeKeyword = { link = "VesperPurple" },
    xmlCdataStart = { link = "VesperGray" },
    xmlCdataCdata = { link = "VesperPurple" },
    dtdFunction = { link = "VesperGray" },
    dtdTagName = { link = "VesperPurple" },
    xmlAttrib = { link = "VesperOrange" },
    xmlProcessingDelim = { link = "VesperGray" },
    dtdParamEntityPunct = { link = "VesperGray" },
    dtdParamEntityDPunct = { link = "VesperGray" },
    xmlAttribPunct = { link = "VesperGray" },
    xmlEntity = { link = "VesperRed" },
    xmlEntityPunct = { link = "VesperRed" },
    clojureKeyword = { link = "VesperBlue" },
    clojureCond = { link = "VesperOrange" },
    clojureSpecial = { link = "VesperOrange" },
    clojureDefine = { link = "VesperOrange" },
    clojureFunc = { link = "VesperYellow" },
    clojureRepeat = { link = "VesperYellow" },
    clojureCharacter = { link = "VesperAqua" },
    clojureStringEscape = { link = "VesperAqua" },
    clojureException = { link = "VesperRed" },
    clojureRegexp = { link = "VesperAqua" },
    clojureRegexpEscape = { link = "VesperAqua" },
    clojureRegexpCharClass = { fg = colors.fg3, bold = config.bold },
    clojureRegexpMod = { link = "clojureRegexpCharClass" },
    clojureRegexpQuantifier = { link = "clojureRegexpCharClass" },
    clojureParen = { link = "VesperFg3" },
    clojureAnonArg = { link = "VesperYellow" },
    clojureVariable = { link = "VesperBlue" },
    clojureMacro = { link = "VesperOrange" },
    clojureMeta = { link = "VesperYellow" },
    clojureDeref = { link = "VesperYellow" },
    clojureQuote = { link = "VesperYellow" },
    clojureUnquote = { link = "VesperYellow" },
    cOperator = { link = "VesperPurple" },
    cppOperator = { link = "VesperPurple" },
    cStructure = { link = "VesperOrange" },
    pythonBuiltin = { link = "VesperOrange" },
    pythonBuiltinObj = { link = "VesperOrange" },
    pythonBuiltinFunc = { link = "VesperOrange" },
    pythonFunction = { link = "VesperAqua" },
    pythonDecorator = { link = "VesperRed" },
    pythonInclude = { link = "VesperBlue" },
    pythonImport = { link = "VesperBlue" },
    pythonRun = { link = "VesperBlue" },
    pythonCoding = { link = "VesperBlue" },
    pythonOperator = { link = "VesperRed" },
    pythonException = { link = "VesperRed" },
    pythonExceptions = { link = "VesperPurple" },
    pythonBoolean = { link = "VesperPurple" },
    pythonDot = { link = "VesperFg3" },
    pythonConditional = { link = "VesperRed" },
    pythonRepeat = { link = "VesperRed" },
    pythonDottedName = { link = "VesperGreenBold" },
    cssBraces = { link = "VesperBlue" },
    cssFunctionName = { link = "VesperYellow" },
    cssIdentifier = { link = "VesperOrange" },
    cssClassName = { link = "VesperGreen" },
    cssColor = { link = "VesperBlue" },
    cssSelectorOp = { link = "VesperBlue" },
    cssSelectorOp2 = { link = "VesperBlue" },
    cssImportant = { link = "VesperGreen" },
    cssVendor = { link = "VesperFg1" },
    cssTextProp = { link = "VesperAqua" },
    cssAnimationProp = { link = "VesperAqua" },
    cssUIProp = { link = "VesperYellow" },
    cssTransformProp = { link = "VesperAqua" },
    cssTransitionProp = { link = "VesperAqua" },
    cssPrintProp = { link = "VesperAqua" },
    cssPositioningProp = { link = "VesperYellow" },
    cssBoxProp = { link = "VesperAqua" },
    cssFontDescriptorProp = { link = "VesperAqua" },
    cssFlexibleBoxProp = { link = "VesperAqua" },
    cssBorderOutlineProp = { link = "VesperAqua" },
    cssBackgroundProp = { link = "VesperAqua" },
    cssMarginProp = { link = "VesperAqua" },
    cssListProp = { link = "VesperAqua" },
    cssTableProp = { link = "VesperAqua" },
    cssFontProp = { link = "VesperAqua" },
    cssPaddingProp = { link = "VesperAqua" },
    cssDimensionProp = { link = "VesperAqua" },
    cssRenderProp = { link = "VesperAqua" },
    cssColorProp = { link = "VesperAqua" },
    cssGeneratedContentProp = { link = "VesperAqua" },
    javaScriptBraces = { link = "VesperFg1" },
    javaScriptFunction = { link = "VesperAqua" },
    javaScriptIdentifier = { link = "VesperRed" },
    javaScriptMember = { link = "VesperBlue" },
    javaScriptNumber = { link = "VesperPurple" },
    javaScriptNull = { link = "VesperPurple" },
    javaScriptParens = { link = "VesperFg3" },
    typescriptReserved = { link = "VesperAqua" },
    typescriptLabel = { link = "VesperAqua" },
    typescriptFuncKeyword = { link = "VesperAqua" },
    typescriptIdentifier = { link = "VesperOrange" },
    typescriptBraces = { link = "VesperFg1" },
    typescriptEndColons = { link = "VesperFg1" },
    typescriptDOMObjects = { link = "VesperFg1" },
    typescriptAjaxMethods = { link = "VesperFg1" },
    typescriptLogicSymbols = { link = "VesperFg1" },
    typescriptDocSeeTag = { link = "Comment" },
    typescriptDocParam = { link = "Comment" },
    typescriptDocTags = { link = "vimCommentTitle" },
    typescriptGlobalObjects = { link = "VesperFg1" },
    typescriptParens = { link = "VesperFg3" },
    typescriptOpSymbols = { link = "VesperFg3" },
    typescriptHtmlElemProperties = { link = "VesperFg1" },
    typescriptNull = { link = "VesperPurple" },
    typescriptInterpolationDelimiter = { link = "VesperAqua" },
    purescriptModuleKeyword = { link = "VesperAqua" },
    purescriptModuleName = { link = "VesperFg1" },
    purescriptWhere = { link = "VesperAqua" },
    purescriptDelimiter = { link = "VesperFg4" },
    purescriptType = { link = "VesperFg1" },
    purescriptImportKeyword = { link = "VesperAqua" },
    purescriptHidingKeyword = { link = "VesperAqua" },
    purescriptAsKeyword = { link = "VesperAqua" },
    purescriptStructure = { link = "VesperAqua" },
    purescriptOperator = { link = "VesperBlue" },
    purescriptTypeVar = { link = "VesperFg1" },
    purescriptConstructor = { link = "VesperFg1" },
    purescriptFunction = { link = "VesperFg1" },
    purescriptConditional = { link = "VesperOrange" },
    purescriptBacktick = { link = "VesperOrange" },
    coffeeExtendedOp = { link = "VesperFg3" },
    coffeeSpecialOp = { link = "VesperFg3" },
    coffeeCurly = { link = "VesperOrange" },
    coffeeParen = { link = "VesperFg3" },
    coffeeBracket = { link = "VesperOrange" },
    rubyStringDelimiter = { link = "VesperGreen" },
    -- rubyInterpolationDelimiter = { link = "VesperAqua" },
    rubyDefinedOperator = { link = "rubyKeyword" },
    objcTypeModifier = { link = "VesperRed" },
    objcDirective = { link = "VesperBlue" },
    goDirective = { link = "VesperAqua" },
    goConstants = { link = "VesperPurple" },
    goDeclaration = { link = "VesperRed" },
    goDeclType = { link = "VesperBlue" },
    goBuiltins = { link = "VesperOrange" },
    luaIn = { link = "VesperRed" },
    luaFunction = { link = "VesperAqua" },
    luaTable = { link = "VesperOrange" },
    moonSpecialOp = { link = "VesperFg3" },
    moonExtendedOp = { link = "VesperFg3" },
    moonFunction = { link = "VesperFg3" },
    moonObject = { link = "VesperYellow" },
    javaAnnotation = { link = "VesperBlue" },
    javaDocTags = { link = "VesperAqua" },
    javaCommentTitle = { link = "vimCommentTitle" },
    javaParen = { link = "VesperFg3" },
    javaParen1 = { link = "VesperFg3" },
    javaParen2 = { link = "VesperFg3" },
    javaParen3 = { link = "VesperFg3" },
    javaParen4 = { link = "VesperFg3" },
    javaParen5 = { link = "VesperFg3" },
    javaOperator = { link = "VesperOrange" },
    javaVarArg = { link = "VesperGreen" },
    elixirDocString = { link = "Comment" },
    elixirStringDelimiter = { link = "VesperGreen" },
    elixirInterpolationDelimiter = { link = "VesperAqua" },
    elixirModuleDeclaration = { link = "VesperYellow" },
    scalaNameDefinition = { link = "VesperFg1" },
    scalaCaseFollowing = { link = "VesperFg1" },
    scalaCapitalWord = { link = "VesperFg1" },
    scalaTypeExtension = { link = "VesperFg1" },
    scalaKeyword = { link = "VesperRed" },
    scalaKeywordModifier = { link = "VesperRed" },
    scalaSpecial = { link = "VesperAqua" },
    scalaOperator = { link = "VesperFg1" },
    scalaTypeDeclaration = { link = "VesperYellow" },
    scalaTypeTypePostDeclaration = { link = "VesperYellow" },
    scalaInstanceDeclaration = { link = "VesperFg1" },
    scalaInterpolation = { link = "VesperAqua" },
    markdownItalic = { fg = colors.fg3, italic = true },
    markdownBold = { fg = colors.fg3, bold = config.bold },
    markdownBoldItalic = { fg = colors.fg3, bold = config.bold, italic = true },
    markdownH1 = { link = "VesperGreenBold" },
    markdownH2 = { link = "VesperGreenBold" },
    markdownH3 = { link = "VesperYellowBold" },
    markdownH4 = { link = "VesperYellowBold" },
    markdownH5 = { link = "VesperYellow" },
    markdownH6 = { link = "VesperYellow" },
    markdownCode = { link = "VesperAqua" },
    markdownCodeBlock = { link = "VesperAqua" },
    markdownCodeDelimiter = { link = "VesperAqua" },
    markdownBlockquote = { link = "VesperGray" },
    markdownListMarker = { link = "VesperGray" },
    markdownOrderedListMarker = { link = "VesperGray" },
    markdownRule = { link = "VesperGray" },
    markdownHeadingRule = { link = "VesperGray" },
    markdownUrlDelimiter = { link = "VesperFg3" },
    markdownLinkDelimiter = { link = "VesperFg3" },
    markdownLinkTextDelimiter = { link = "VesperFg3" },
    markdownHeadingDelimiter = { link = "VesperOrange" },
    markdownUrl = { link = "VesperPurple" },
    markdownUrlTitleDelimiter = { link = "VesperGreen" },
    markdownLinkText = { fg = colors.gray, underline = config.underline },
    markdownIdDeclaration = { link = "markdownLinkText" },
    haskellType = { link = "VesperBlue" },
    haskellIdentifier = { link = "VesperAqua" },
    haskellSeparator = { link = "VesperFg4" },
    haskellDelimiter = { link = "VesperOrange" },
    haskellOperators = { link = "VesperPurple" },
    haskellBacktick = { link = "VesperOrange" },
    haskellStatement = { link = "VesperPurple" },
    haskellConditional = { link = "VesperPurple" },
    haskellLet = { link = "VesperRed" },
    haskellDefault = { link = "VesperRed" },
    haskellWhere = { link = "VesperRed" },
    haskellBottom = { link = "VesperRedBold" },
    haskellImportKeywords = { link = "VesperPurpleBold" },
    haskellDeclKeyword = { link = "VesperOrange" },
    haskellDecl = { link = "VesperOrange" },
    haskellDeriving = { link = "VesperPurple" },
    haskellAssocType = { link = "VesperAqua" },
    haskellNumber = { link = "VesperAqua" },
    haskellPragma = { link = "VesperRedBold" },
    haskellTH = { link = "VesperAquaBold" },
    haskellForeignKeywords = { link = "VesperGreen" },
    haskellKeyword = { link = "VesperRed" },
    haskellFloat = { link = "VesperAqua" },
    haskellInfix = { link = "VesperPurple" },
    haskellQuote = { link = "VesperGreenBold" },
    haskellShebang = { link = "VesperYellowBold" },
    haskellLiquid = { link = "VesperPurpleBold" },
    haskellQuasiQuoted = { link = "VesperBlueBold" },
    haskellRecursiveDo = { link = "VesperPurple" },
    haskellQuotedType = { link = "VesperRed" },
    haskellPreProc = { link = "VesperFg4" },
    haskellTypeRoles = { link = "VesperRedBold" },
    haskellTypeForall = { link = "VesperRed" },
    haskellPatternKeyword = { link = "VesperBlue" },
    jsonKeyword = { link = "VesperGreen" },
    jsonQuote = { link = "VesperGreen" },
    jsonBraces = { link = "VesperFg1" },
    jsonString = { link = "VesperFg1" },
    mailQuoted1 = { link = "VesperAqua" },
    mailQuoted2 = { link = "VesperPurple" },
    mailQuoted3 = { link = "VesperYellow" },
    mailQuoted4 = { link = "VesperGreen" },
    mailQuoted5 = { link = "VesperRed" },
    mailQuoted6 = { link = "VesperOrange" },
    mailSignature = { link = "Comment" },
    csBraces = { link = "VesperFg1" },
    csEndColon = { link = "VesperFg1" },
    csLogicSymbols = { link = "VesperFg1" },
    csParens = { link = "VesperFg3" },
    csOpSymbols = { link = "VesperFg3" },
    csInterpolationDelimiter = { link = "VesperFg3" },
    csInterpolationAlignDel = { link = "VesperAquaBold" },
    csInterpolationFormat = { link = "VesperAqua" },
    csInterpolationFormatDel = { link = "VesperAquaBold" },
    rustSigil = { link = "VesperOrange" },
    rustEscape = { link = "VesperAqua" },
    rustStringContinuation = { link = "VesperAqua" },
    rustEnum = { link = "VesperAqua" },
    rustStructure = { link = "VesperAqua" },
    rustModPathSep = { link = "VesperFg2" },
    rustCommentLineDoc = { link = "Comment" },
    rustDefault = { link = "VesperAqua" },
    ocamlOperator = { link = "VesperFg1" },
    ocamlKeyChar = { link = "VesperOrange" },
    ocamlArrow = { link = "VesperOrange" },
    ocamlInfixOpKeyword = { link = "VesperRed" },
    ocamlConstructor = { link = "VesperOrange" },
    LspSagaCodeActionTitle = { link = "Title" },
    LspSagaCodeActionBorder = { link = "VesperFg1" },
    LspSagaCodeActionContent = { fg = colors.green, bold = config.bold },
    LspSagaLspFinderBorder = { link = "VesperFg1" },
    LspSagaAutoPreview = { link = "VesperOrange" },
    TargetWord = { fg = colors.blue, bold = config.bold },
    FinderSeparator = { link = "VesperAqua" },
    LspSagaDefPreviewBorder = { link = "VesperBlue" },
    LspSagaHoverBorder = { link = "VesperOrange" },
    LspSagaRenameBorder = { link = "VesperBlue" },
    LspSagaDiagnosticSource = { link = "VesperOrange" },
    LspSagaDiagnosticBorder = { link = "VesperPurple" },
    LspSagaDiagnosticHeader = { link = "VesperGreen" },
    LspSagaSignatureHelpBorder = { link = "VesperGreen" },
    SagaShadow = { link = "VesperBg0" },
    DashboardShortCut = { link = "VesperOrange" },
    DashboardHeader = { link = "VesperAqua" },
    DashboardCenter = { link = "VesperYellow" },
    DashboardFooter = { fg = colors.purple, italic = true },
    MasonHighlight = { link = "VesperAqua"},
    MasonHighlightBlock = { fg = colors.bg0, bg = colors.blue },
    MasonHighlightBlockBold = { fg = colors.bg0, bg = colors.blue, bold = true },
    MasonHighlightSecondary = { fg = colors.yellow },
    MasonHighlightBlockSecondary = { fg = colors.bg0, bg = colors.yellow },
    MasonHighlightBlockBoldSecondary = { fg = colors.bg0, bg = colors.yellow, bold = true },
    MasonHeader = { link = "MasonHighlightBlockBoldSecondary" },
    MasonHeaderSecondary = { link = "MasonHighlightBlockBold" },
    MasonMuted = { fg = colors.fg4 },
    MasonMutedBlock = { fg = colors.bg0, bg = colors.fg4 },
    MasonMutedBlockBold = { fg = colors.bg0, bg = colors.fg4, bold = true },
    LspInlayHint = { link = "comment" },
    CarbonFile = { link = "VesperFg1" },
    CarbonExe = { link = "VesperYellow" },
    CarbonSymlink = { link = "VesperAqua" },
    CarbonBrokenSymlink = { link = "VesperRed" },
    CarbonIndicator = { link = "VesperGray" },
    CarbonDanger = { link = "VesperRed" },
    CarbonPending = { link = "VesperYellow" },
    NoiceCursor = { link = "TermCursor" },
    NotifyDEBUGBorder = { link = "VesperBlue" },
    NotifyDEBUGIcon = { link = "VesperBlue" },
    NotifyDEBUGTitle = { link = "VesperBlue" },
    NotifyERRORBorder = { link = "VesperRed" },
    NotifyERRORIcon = { link = "VesperRed" },
    NotifyERRORTitle = { link = "VesperRed" },
    NotifyINFOBorder = { link = "VesperAqua" },
    NotifyINFOIcon = { link = "VesperAqua" },
    NotifyINFOTitle = { link = "VesperAqua" },
    NotifyTRACEBorder = { link = "VesperGreen" },
    NotifyTRACEIcon = { link = "VesperGreen" },
    NotifyTRACETitle = { link = "VesperGreen" },
    NotifyWARNBorder = { link = "VesperYellow" },
    NotifyWARNIcon = { link = "VesperYellow" },
    NotifyWARNTitle = { link = "VesperYellow" },
    IlluminatedWordText = { link = "LspReferenceText" },
    IlluminatedWordRead = { link = "LspReferenceRead" },
    IlluminatedWordWrite = { link = "LspReferenceWrite" },
    TSRainbowRed = { fg = colors.red },
    TSRainbowOrange = { fg = colors.orange },
    TSRainbowYellow = { fg = colors.yellow },
    TSRainbowGreen = { fg = colors.green },
    TSRainbowBlue = { fg = colors.blue },
    TSRainbowViolet = { fg = colors.purple },
    TSRainbowCyan = { fg = colors.cyan },
    DapBreakpointSymbol = { fg = colors.red, bg = colors.bg1 },
    DapStoppedSymbol = { fg = colors.green, bg = colors.bg1 },
    DapUIBreakpointsCurrentLine = { link = "VesperYellow" },
    DapUIBreakpointsDisabledLine = { link = "VesperGray" },
    DapUIBreakpointsInfo = { link = "VesperAqua" },
    DapUIBreakpointsLine = { link = "VesperYellow" },
    DapUIBreakpointsPath = { link = "VesperBlue" },
    DapUICurrentFrameName = { link = "VesperPurple" },
    DapUIDecoration = { link = "VesperPurple" },
    DapUIEndofBuffer = { link = "VesperBg2" },
    DapUIFloatBorder = { link = "VesperAqua" },
    DapUILineNumber = { link = "VesperYellow" },
    DapUIModifiedValue = { link = "VesperRed" },
    DapUIPlayPause = { fg = colors.green, bg = colors.bg1 },
    DapUIRestart = { fg = colors.green, bg = colors.bg1 },
    DapUIScope = { link = "VesperBlue" },
    DapUISource = { link = "VesperFg1" },
    DapUIStepBack = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepInto = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepOut = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepOver = { fg = colors.blue, bg = colors.bg1 },
    DapUIStop = { fg = colors.red, bg = colors.bg1 },
    DapUIStoppedThread = { link = "VesperBlue" },
    DapUIThread = { link = "VesperBlue" },
    DapUIType = { link = "VesperOrange" },
    DapUIUnavailable = { link = "VesperGray" },
    DapUIWatchesEmpty = { link = "VesperGray" },
    DapUIWatchesError = { link = "VesperRed" },
    DapUIWatchesValue = { link = "VesperYellow" },
    DapUIWinSelect = { link = "VesperYellow" },
    NeogitDiffDelete = { link = "DiffDelete" },
    NeogitDiffAdd = { link = "DiffAdd" },
    NeogitHunkHeader = { link = "WinBar" },
    NeogitHunkHeaderHighlight = { link = "WinBarNC" },
    DiffviewStatusModified = { link = "VesperGreenBold" },
    DiffviewFilePanelInsertions = { link = "VesperGreenBold" },
    DiffviewFilePanelDeletions = { link = "VesperRedBold" },
    ["@comment"] = { link = "Comment" },
    ["@none"] = { bg = "NONE", fg = "NONE" },
    ["@preproc"] = { link = "PreProc" },
    ["@define"] = { link = "Define" },
    ["@operator"] = { link = "Operator" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { link = "Delimiter" },
    ["@punctuation.special"] = { link = "Delimiter" },
    ["@string"] = { link = "String" },
    ["@string.regex"] = { link = "String" },
    ["@string.escape"] = { link = "SpecialChar" },
    ["@string.special"] = { link = "SpecialChar" },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@boolean"] = { link = "Boolean" },
    ["@number"] = { link = "Number" },
    ["@float"] = { link = "Float" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { link = "Special" },
    ["@function.call"] = { link = "Function" },
    ["@function.macro"] = { link = "Macro" },
    ["@method"] = { link = "Function" },
    ["@method.call"] = { link = "Function" },
    ["@constructor"] = { link = "Special" },
    ["@parameter"] = { link = "Identifier" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.operator"] = { link = "VesperRed" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@conditional"] = { link = "Conditional" },
    ["@repeat"] = { link = "Repeat" },
    ["@debug"] = { link = "Debug" },
    ["@label"] = { link = "Label" },
    ["@include"] = { link = "Include" },
    ["@exception"] = { link = "Exception" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { link = "Type" },
    ["@type.definition"] = { link = "Typedef" },
    ["@type.qualifier"] = { link = "Type" },
    ["@storageclass"] = { link = "StorageClass" },
    ["@attribute"] = { link = "PreProc" },
    ["@field"] = { link = "Identifier" },
    ["@property"] = { link = "Identifier" },
    ["@variable"] = { link = "VesperFg1" },
    ["@variable.builtin"] = { link = "Special" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Special" },
    ["@constant.macro"] = { link = "Define" },
    ["@namespace"] = { link = "VesperFg1" },
    ["@symbol"] = { link = "Identifier" },
    ["@text"] = { link = "VesperFg1" },
    ["@text.strong"] = { bold = config.bold },
    ["@text.emphasis"] = { italic = config.italic.emphasis },
    ["@text.underline"] = { underline = config.underline },
    ["@text.strike"] = { strikethrough = config.strikethrough },
    ["@text.title"] = { link = "Title" },
    ["@text.literal"] = { link = "String" },
    ["@text.uri"] = { link = "Underlined" },
    ["@text.math"] = { link = "Special" },
    ["@text.environment"] = { link = "Macro" },
    ["@text.environment.name"] = { link = "Type" },
    ["@text.reference"] = { link = "Constant" },
    ["@text.todo"] = { link = "Todo" },
    ["@text.todo.checked"] = { link = "VesperGreen" },
    ["@text.todo.unchecked"] = { link = "VesperGray" },
    ["@text.note"] = { link = "SpecialComment" },
    ["@text.note.comment"] = { fg = colors.purple, bold = config.bold },
    ["@text.warning"] = { link = "WarningMsg" },
    ["@text.danger"] = { link = "ErrorMsg" },
    ["@text.danger.comment"] = { fg = colors.fg0, bg = colors.red, bold = config.bold },
    ["@text.diff.add"] = { link = "diffAdded" },
    ["@text.diff.delete"] = { link = "diffRemoved" },
    ["@tag"] = { link = "Tag" },
    ["@tag.attribute"] = { link = "Identifier" },
    ["@tag.delimiter"] = { link = "Delimiter" },
    ["@punctuation"] = { link = "Delimiter" },
    ["@macro"] = { link = "Macro" },
    ["@structure"] = { link = "Structure" },
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.comment"] = { link = "@comment" },
    ["@lsp.type.decorator"] = { link = "@macro" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.interface"] = { link = "@constructor" },
    ["@lsp.type.macro"] = { link = "@macro" },
    ["@lsp.type.method"] = { link = "@method" },
    ["@lsp.type.namespace"] = { link = "@namespace" },
    ["@lsp.type.parameter"] = { link = "@parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type.definition" },
    ["@lsp.type.variable"] = { link = "@variable" },
  },

  for group, hl in pairs(config.overrides) do
    if groups[group] then
      -- "link" should not mix with other configs (:h hi-link)
      groups[group].link = nil
    end

    groups[group] = vim.tbl_extend("force", groups[group] or {}, hl)
  end

  return groups
end

-- -@param config VesperConfig?
Vesper.setup = function(config)
  Vesper.config = vim.tbl_deep_extend("force", Vesper.config, config or {})
end

--- main load function
Vesper.load = function()
  if vim.version().minor < 8 then
    vim.notify_once("vesper.nvim: you must use neovim 0.8 or higher")
    return
  end

  -- reset colors
  if vim.g.colors_name then
    vim.cmd.hi("clear")
  end
  vim.g.colors_name = "vesper"
  vim.o.termguicolors = true

  local groups = get_groups()

  -- add highlights
  for group, settings in pairs(groups) do
    vim.api.nvim_set_hl(0, group, settings)
  end
end

return Vesper
